version: 2
jobs:
  build:
    docker:
      - image: samueldebruyn/debian-git

    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Look at files
          command: ls