version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout
      - run:
          name: Python Test
          command: .circleci/test-devsite.py
      - run:
          name: Look at files
          command: cd src
          command: ls